language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
r_github_packages:
- statnet/statnet.common
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
